import { Sequelize } from "sequelize";
import dotenv from "dotenv";
dotenv.config();

const DATABASE_REALTIME = process.env.DATABASE_REALTIME;
const DATABASE_USERNAME_REALTIME = process.env.DATABASE_USERNAME_REALTIME;
const DATABASE_PASSWORD_REALTIME = process.env.DATABASE_PASSWORD_REALTIME;
const DATABASE_HOST_REALTIME = process.env.DATABASE_HOST_REALTIME;
const DATABASE_PORT_REALTIME = process.env.DATABASE_PORT_REALTIME;
const DATABASE_TYPE_REALTIME = process.env.DATABASE_TYPE_REALTIME;
const DATABASE_LOGGING_REALTIME = process.env.DATABSE_LOGGING_REALTIME;

const DBREALTIME = new Sequelize(
  DATABASE_REALTIME,
  DATABASE_USERNAME_REALTIME,
  DATABASE_PASSWORD_REALTIME,
  {
    host: DATABASE_HOST_REALTIME,
    port: DATABASE_PORT_REALTIME,
    dialect: DATABASE_TYPE_REALTIME,
    logging: DATABASE_LOGGING_REALTIME,
    timezone: "+07:00",
  }
);

export default DBREALTIME;
